# Generated by Django 2.2.4 on 2019-08-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер телефона фирмы')),
                ('slug', models.SlugField(max_length=150)),
                ('body', models.TextField(blank=True, verbose_name='Описание фирмы')),
                ('start_time', models.TimeField(unique=True)),
                ('end_time', models.TimeField(unique=True)),
                ('city', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('comments', models.TextField(verbose_name='Отзывы')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_m', models.CharField(max_length=30, unique=True)),
                ('number_m', models.ImageField(blank=True, upload_to='', verbose_name='Номер мастера')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Company')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'db_table': 'masters',
            },
        ),
        migrations.CreateModel(
            name='Masters_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Masters')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(unique=True)),
                ('month', models.IntegerField(unique=True)),
                ('day', models.IntegerField(unique=True)),
                ('time', models.TimeField(unique=True)),
                ('procedure', models.CharField(max_length=30, unique=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Masters')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Даты',
                'db_table': 'date',
            },
        ),
    ]
