# Generated by Django 2.2.4 on 2019-08-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0004_auto_20190820_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Картинка '),
        ),
    ]
