# Generated by Django 2.2.4 on 2019-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0005_auto_20190821_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/flesh/images/dinamic_img', verbose_name='Картинка '),
        ),
    ]
