# Generated by Django 2.2.4 on 2019-08-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0006_auto_20190821_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='images_company', verbose_name='Картинка '),
        ),
    ]
