# Generated by Django 2.2.4 on 2019-08-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0007_auto_20190821_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='image',
            field=models.ImageField(blank=True, upload_to='flesh/images/dinamic_img', verbose_name='Фото '),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='flesh/images/dinamic_img', verbose_name='Картинка '),
        ),
        migrations.AlterField(
            model_name='company',
            name='login',
            field=models.CharField(max_length=20, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=20, unique=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='masters_content',
            name='images',
            field=models.ImageField(blank=True, upload_to='flesh/images/dinamic_img'),
        ),
    ]
