# Generated by Django 2.2.4 on 2019-08-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0009_auto_20190822_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка '),
        ),
    ]
