# Generated by Django 2.2.4 on 2019-08-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0010_auto_20190822_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='flesh/static/images/dinamic_img/', verbose_name='Картинка '),
        ),
        migrations.AlterField(
            model_name='masters',
            name='image',
            field=models.ImageField(blank=True, upload_to='flesh/static/images/dinamic_img/', verbose_name='Фото '),
        ),
        migrations.AlterField(
            model_name='masters_content',
            name='images',
            field=models.ImageField(blank=True, upload_to='flesh/static/images/foto_m/foto_cont/'),
        ),
    ]
