# Generated by Django 2.2.4 on 2019-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0011_auto_20190822_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_comp', verbose_name='Картинка '),
        ),
        migrations.AlterField(
            model_name='masters_content',
            name='images',
            field=models.ImageField(blank=True, upload_to='flesh/static/flesh/images/foto_m/foto_cont/'),
        ),
    ]
