# Generated by Django 2.2.4 on 2019-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0012_auto_20190823_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=50, unique=True)),
                ('cash', models.IntegerField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'operation',
            },
        ),
    ]
