# Generated by Django 2.2.4 on 2019-11-04 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0014_operations_companys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='masters_content',
            name='images',
        ),
        migrations.AddField(
            model_name='date',
            name='date_as',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='masters_content',
            name='description',
            field=models.TextField(default='no description', verbose_name='Описание деятельности мастера'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='image_comp', verbose_name='Картинка '),
        ),
        migrations.AlterField(
            model_name='date',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='masters',
            name='name_m',
            field=models.CharField(max_length=30, verbose_name='Имя мастера'),
        ),
        migrations.AlterField(
            model_name='masters',
            name='number_m',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Номер мастера'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='cash',
            field=models.IntegerField(verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='operation',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='time',
            field=models.TimeField(verbose_name='Время на услугу'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Company')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Date')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Operations')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='MastersImagesDiploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_diploma', models.ImageField(unique=True, upload_to='image_comp', verbose_name='Картинка ')),
                ('description_d', models.TextField(verbose_name='Описание фото')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Masters')),
            ],
        ),
        migrations.CreateModel(
            name='MastersImagesContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_diploma', models.ImageField(unique=True, upload_to='image_comp', verbose_name='Картинка ')),
                ('description_c', models.TextField(verbose_name='Описание фото')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Masters')),
            ],
        ),
    ]
