# Generated by Django 2.2.4 on 2020-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0016_auto_20191106_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(default='No_name', max_length=50, unique=True, verbose_name='Имя Заказщика'),
        ),
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.CharField(default='No_telephone', max_length=50, unique=True, verbose_name='Телефон заказчика'),
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.IntegerField(default=5, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='date',
            name='month',
            field=models.IntegerField(default=3, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='date',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='Год'),
        ),
    ]
