# Generated by Django 2.2.4 on 2020-03-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0017_auto_20200305_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='description',
            field=models.TextField(default='no description', verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.IntegerField(default=7, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='date',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
