# Generated by Django 2.2.4 on 2020-05-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0019_auto_20200406_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operations',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.RenameField(
            model_name='operations',
            old_name='operation',
            new_name='name_operations',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='companys',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='description',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='time',
        ),
        migrations.AddField(
            model_name='company',
            name='commission',
            field=models.CharField(choices=[('full', 'Full'), ('one-time', 'One-time')], default='one-time', max_length=10),
        ),
        migrations.AddField(
            model_name='masterstatistics',
            name='master',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='flesh.Masters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flesh.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.IntegerField(default=18, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='date',
            name='month',
            field=models.IntegerField(default=5, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='masterstatistics',
            name='persent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Оценка качества'),
        ),
        migrations.CreateModel(
            name='OperationsDetail',
            fields=[
                ('operations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flesh.Operations')),
                ('cash', models.IntegerField(verbose_name='Стоимость услуги')),
                ('time', models.TimeField(verbose_name='Время на услугу')),
                ('description', models.TextField(default='no description', verbose_name='Описание услуги')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Masters')),
            ],
            bases=('flesh.operations',),
        ),
    ]
