# Generated by Django 2.2.4 on 2020-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0020_auto_20200518_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threy_month', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('month', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('day', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
