# Generated by Django 2.2.4 on 2020-05-20 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0021_companyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyorder',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flesh.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.IntegerField(default=20, verbose_name='День'),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('visits', models.IntegerField(verbose_name='Посещений')),
                ('number_telephone', models.CharField(max_length=13, unique=True, verbose_name='Пароль')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Company')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='clients',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flesh.Clients'),
            preserve_default=False,
        ),
    ]
