# Generated by Django 2.2.4 on 2020-05-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0022_auto_20200520_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=0, max_length=50, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='number',
            field=models.CharField(default=0, max_length=13, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='number_telephone',
            field=models.CharField(max_length=13, unique=True, verbose_name='Номер телефона'),
        ),
    ]
