# Generated by Django 2.2.4 on 2020-06-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0023_auto_20200520_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersimagescontent',
            name='description_c',
        ),
        migrations.RemoveField(
            model_name='mastersimagescontent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mastersimagescontent',
            name='images_diploma',
        ),
        migrations.RemoveField(
            model_name='mastersimagescontent',
            name='master',
        ),
        migrations.RemoveField(
            model_name='mastersimagesdiploma',
            name='description_d',
        ),
        migrations.RemoveField(
            model_name='mastersimagesdiploma',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mastersimagesdiploma',
            name='master',
        ),
        migrations.AddField(
            model_name='mastersimagescontent',
            name='images_content',
            field=models.ImageField(default=0, upload_to='masters_img/masters_content', verbose_name='MasterImageContent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastersimagescontent',
            name='masters_content_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flesh.Masters_Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastersimagesdiploma',
            name='masters_content_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flesh.Masters_Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.IntegerField(default=6, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='date',
            name='month',
            field=models.IntegerField(default=6, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='mastersimagesdiploma',
            name='images_diploma',
            field=models.ImageField(upload_to='masters_img/masters_diploma', verbose_name='MasterImageDiplom'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='ФИО'),
        ),
        migrations.CreateModel(
            name='MasterOtherSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reiting', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('menuColor', models.CharField(max_length=7, verbose_name='Цвет главного меню')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Masters')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOtherSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reiting', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('menuColor', models.CharField(max_length=7, verbose_name='Цвет главного меню')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flesh.Company')),
            ],
        ),
    ]
