# Generated by Django 2.2.4 on 2020-06-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0024_auto_20200606_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersimagescontent',
            name='images_content',
            field=models.ImageField(unique=True, upload_to='masters_img/masters_content', verbose_name='MasterImageContent'),
        ),
        migrations.AlterField(
            model_name='mastersimagesdiploma',
            name='images_diploma',
            field=models.ImageField(unique=True, upload_to='masters_img/masters_diploma', verbose_name='MasterImageDiplom'),
        ),
    ]
