# Generated by Django 2.2.4 on 2020-06-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flesh', '0025_auto_20200606_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='0', max_length=14, unique=True, verbose_name='Номер телефона')),
                ('name', models.CharField(default='0', max_length=14, verbose_name='Имя владельца')),
                ('discription', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новая компания',
                'verbose_name_plural': 'Новые компании',
                'db_table': 'new_company',
            },
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.IntegerField(default=8, verbose_name='День'),
        ),
    ]
